CREATE DATABASE IF NOT EXISTS nbxplorer; 
CREATE DATABASE IF NOT EXISTS btcpayserver; 
GRANT ALL PRIVILEGES ON DATABASE nbxplorer TO postgres; 
GRANT ALL PRIVILEGES ON DATABASE btcpayserver TO postgres; 
